config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
    namespace :admin do
      resources :pricelists do
        collection do
          get 'new_import'
          post "import"
        end
      end
      resources :conflicts, only: [:index, :update, :destroy]
      resources :products do
        resources :product_synonims
      end
    end
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/conflict.rb
class Spree::Conflict < ActiveRecord::Base
  belongs_to :pricelist
  validates :product_name, uniqueness: true

  def suitable_products
    Spree::ProductSynonim.name_matching(product_name).first(10)
  end

  def select_options_for_suitable_products
    options = {}
    suitable_products.each{|p| options[p.attributes["name"]] = p.attributes["product_id"]}
    options
  end

  def solve(attrs)
    action = attrs[:action]
    if action == "update_product"
      product = Spree::Product.find(attrs[:product])
      product.add_synonim(self.product_name)
      new_product_attrs = {}
      new_product_attrs[:price] = self.price.to_f if self.price.to_f > 0
      new_product_attrs[:cost_price] = self.cost_price.to_f if self.cost_price.to_f > 0
      new_product_attrs[:pricelist_id] = self.pricelist_id
      product.update_attributes(new_product_attrs)
      product.update_stock_from_pricelist(new_product_attrs.merge('quantity' => self.quantity))
    else
      product = Spree::Product.create(name: self.product_name, sku: self.sku, price: self.price.to_f, cost_price: self.cost_price.to_f, pricelist_id: self.pricelist_id, shipping_category_id: Spree::ShippingCategory.first.id)
    end
    self.destroy if product.persisted?
    product
  end
end

app/models/spree/pricelist.rb
class Spree::Pricelist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/models/spree/product_decorator.rb
require 'pg_search'
Spree::Product.class_eval do
  include PgSearch

  has_many :product_synonims, class_name: 'Spree::ProductSynonim', dependent: :destroy
  belongs_to :pricelist

  before_update :update_synonim, if: lambda {|product| product.name_changed? }
  after_create :add_synonim

  scope :find_by_synonim, lambda { |name| joins(:product_synonims).where("spree_product_synonims.name = ?", name).limit(1)}

  pg_search_scope :name_matching,
    associated_against: {product_synonims: :name},
    using: {
      trigram: {},
      tsearch: {dictionary: "russian", any_word: true}
    },
    ranked_by: "1.2 * :trigram + 0.5 * :tsearch"

  self.whitelisted_ransackable_associations += %w[pricelist]

  def add_synonim(product_name=nil)
    self.product_synonims.find_or_create_by(:name => product_name || self.name)
  end

  def update_stock_from_pricelist(attrs)
      stock_location = Spree::StockLocation.active.first
      if stock_location
          # if pricelist has quantity column, we update quantity
          # stock location should be backorderable: false by default
          # otherwise: we set products as backorderable
          if attrs['quantity'].present?
              # clear current quantity - reset to 0 before setting new quantity
              stock_location.unstock(self.master, stock_location.count_on_hand(self.master))
              stock_movement = stock_location.stock_movements.build(quantity: attrs['quantity'])
              stock_movement.stock_item = stock_location.set_up_stock_item(self.master)
              stock_movement.stock_item.update_attributes(backorderable: false)
              stock_movement.save!
          else
              stock_item = stock_location.stock_item_or_create(self.master)
              stock_item.update_attributes(backorderable: true)
          end
      end
  end

  protected

  def update_synonim
    self.product_synonims.where(name: self.name_was).first.try(:update_attributes, {name: self.name})
  end
end

app/models/spree/product_synonim.rb
class Spree::ProductSynonim < ActiveRecord::Base

  validates :name, uniqueness: true, presence: true

  belongs_to :product

  include PgSearch

  pg_search_scope :name_matching,
    against: :name ,
    using: {
      tsearch: {dictionary: "english", any_word: true,:tsvector_column => 'tsv_name'}
    },
    ranked_by: "1.2 * :trigram + 0.5 * :tsearch"

    def product
      Spree::Product.find_by_id(self.product_id)
    end

end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do

  def update_stock_from_pricelist(attrs)
      stock_location = Spree::StockLocation.active.first
      if stock_location
          # if pricelist has quantity column, we update quantity
          # stock location should be backorderable: false by default
          # otherwise: we set products as backorderable
          if attrs['quantity'].present?
              # clear current quantity - reset to 0 before setting new quantity
              stock_location.unstock(self, stock_location.count_on_hand(self))
              stock_movement = stock_location.stock_movements.build(quantity: attrs['quantity'])
              stock_movement.stock_item = stock_location.set_up_stock_item(self)
              stock_movement.stock_item.update_attributes(backorderable: false)
              stock_movement.save!
          else
              stock_item = stock_location.stock_item_or_create(self)
              stock_item.update_attributes(backorderable: true)
          end
      end
  end

  private

    def set_master_out_of_stock
        if product.master && product.master.in_stock?
          product.master.stock_items.update_all(:backorderable => false)
          # product.master.stock_items.each { |item| item.reduce_count_on_hand_to_zero }
        end
      end
end

app/controllers/spree/admin/conflicts_controller.rb
module Spree
  module Admin
    class ConflictsController < ResourceController
      def index
        @conflicts = Spree::Conflict.order('created_at desc').page(params[:page]).per(5)
      end

      def update
        @conflict = Spree::Conflict.find params[:id]
        @product = @conflict.solve(params[:conflict])
      end
    end
  end
end

app/controllers/spree/admin/pricelists_controller.rb
 module Spree
  module Admin
    class PricelistsController < BaseController
      def index
        @pricelists = Spree::Pricelist.all
      end

      def new
        @pricelist = Spree::Pricelist.new
      end

      def create
        @pricelist = Spree::Pricelist.new(pricelist_params)
        if @pricelist.save
          flash[:success] = flash_message_for(@pricelist, :successfully_created)
          redirect_to admin_pricelists_path
        else
          respond_with(@pricelist)
        end
      end

      def edit
        @pricelist = Spree::Pricelist.find(params[:id])
      end

      def update
        @pricelist = Spree::Pricelist.find(params[:id])

        if @pricelist.update_attributes(pricelist_params)
          flash[:success] = flash_message_for(@pricelist, :successfully_updated)
          redirect_to admin_pricelists_path
        else
          respond_with(@pricelist)
        end
      end

      def destroy
        @pricelist = Spree::Pricelist.find(params[:id])
        @pricelist.destroy
      end

      def import
        Spree::Importers::BaseImporter.parse(params[:pricelist], params[:xlsx_file],params[:starting_row])
        redirect_to admin_pricelists_path
      end

      protected

      def pricelist_params
        params.require(:pricelist).permit!
      end
    end
  end
end

app/controllers/spree/admin/product_synonims_controller.rb
module Spree
  module Admin
    class ProductSynonimsController < ResourceController
      belongs_to 'spree/product', :find_by => :slug
    end
  end
end

app/helpers/spree/admin/conflicts_helper.rb
module Spree
  module Admin
    module ConflictsHelper
      def conflict_solve_actions
        [:update_product, :create_new_product].map do |action|
          [Spree.t(action), action]
        end
      end
    end
  end
end

app/views/spree/admin/conflicts/_conflict.html.erb
<tr id="<%= dom_id(conflict) %>">
  <td class="align-center" style="border-left: 1px solid #cee1f4;">
    <p>
      <strong><%= Spree::Conflict.human_attribute_name(:product_name) %></strong>:
      <%= conflict.product_name %>
    </p>
    <p>
      <strong><%= Spree::Conflict.human_attribute_name(:sku) %></strong>:
      <%= conflict.sku %>
    </p>
    <p>
      <strong><%= Spree::Conflict.human_attribute_name(:price) %></strong>:
      <%= conflict.price.to_s %>
    </p>
    <p>
      <strong><%= Spree::Conflict.human_attribute_name(:provider_name) %></strong>:
      <%= conflict.pricelist.name %>
    </p>
    <p>
      <icon class="icon-resize-vertical"></icon>
    </p>
    <fieldset class="no-border-bottom no-border-top">
      <span>
        <%= select_tag 'conflict[product]', options_for_select(conflict.select_options_for_suitable_products), class: 'select2 ', style: 'width:100%;' %>
      </span>
    </fieldset>
  </td>
  <td class="align-center" style="vertical-align:bottom;">
    <fieldset class="no-border-bottom no-border-top">
      <div class="field">
        <%= label_tag "Действие" %>
        <span>
          <%= select_tag 'conflict[action]', options_for_select(conflict_solve_actions), class: 'select2 fullwidth' %>
        </span>
      </div>
    </fieldset>
  </td>
  <td class="actions" data-hook="admin_products_index_row_actions" style="vertical-align:bottom;">
    <%= link_to_with_icon 'ok', 'Решить конфликт', '#', {class: "btn btn-sm btn-success edit resolve-conflict", no_text: true, :"data-id" => conflict.id } %>
    <%= link_to_delete conflict, url: admin_conflict_path(conflict), no_text: true %>
  </td>
</tr>

app/views/spree/admin/conflicts/index.html.erb
<% content_for :page_title do %>
  <%= "Конфликты Распознавания" %>
<% end %>
<div id="conflicts-counter">
  <%= "#{Spree::Conflict.count(:id)} #{Spree::Conflict.model_name.human(count: Spree::Conflict.count(:id))}" %>
</div>
<table class="table table-hover" id="listing_conflicts">
  <colgroup>
    <col style="width:70%"></col>
    <col style="width:20%"></col>
    <col style="width:10%"></col>
  </colgroup>
  <thead>
    <tr data-hook="admin_products_index_headers">
      <th>Конфликты</th>
      <th>Решение</th>
      <th class="actions" data-hook="admin_products_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'spree/admin/conflicts/conflict', collection: @conflicts %>
  </tbody>
</table>
<% if Spree::Conflict.count(:id) > 5 %>
  <div class="get-more">
    <a data-remote="true" href="/admin/conflicts?page=2" rel="next">
      Показать еще конфликты
    </a>
  </div>
<% end %>

app/views/spree/admin/conflicts/index.js.erb
$(document).ready(function(){
	$('.get-more').remove()
	$('#listing_conflicts tbody').append('<%= j(render partial: 'spree/admin/conflicts/conflict', collection: @conflicts)%>')
	<% if params[:page].to_i < (Spree::Conflict.select(:id).count(:id) / 5) %>
	$('#listing_conflicts').after('<div class="get-more"><a href="/admin/conflicts?page=<%= params[:page]= params[:page].to_i + 1 %>" data-remote="true" rel="next">Показать еще конфликты</a></div>')
	<% end %>
	$('select.select2').select2()
});

app/views/spree/admin/conflicts/update.js.erb
<% if @product.errors.blank? %>
  $('tr#<%= dom_id(@conflict) %>').fadeOut();
<% else %>
  $("div#content").prepend('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= @product.errors.full_messages.join(', ') %></div>').alert();
<% end %>

app/views/spree/admin/pricelists/_form.html.erb
<div class="row">
  <div class="col-sm-3">
    <h4>Основная информация</h4>
  
    <div class="four columns lh">
      <%= f.field_container :name do %>
        <%= f.label :name, Spree::Pricelist.human_attribute_name(:name) %>
        <span class="required">*</span>
        <br/>
        <%= f.text_field :name, :class => 'fullwidth title' %>
        <%= f.error_message_on :name %>
      <% end %>
    </div>
    <div class="four columns lh">
      <%= f.field_container :sku_column do %>
        <%= f.label :parser_sku_column, Spree::Pricelist.human_attribute_name(:sku_column) %>
        <br/>
        <%= f.text_field :sku_column, :class => 'fullwidth' %>
      <% end %>
    </div>
    <div class="four columns lh">
      <%= f.field_container :name_column do %>
        <%= f.label :parser_name_column, Spree::Pricelist.human_attribute_name(:name_column) %>
        <br/>
        <%= f.text_field :name_column, :class => 'fullwidth' %>
      <% end %>
    </div>
    <div class="four columns lh">
      <%= f.field_container :cost_price_column do %>
        <%= f.label :parser_cost_price_column, Spree::Pricelist.human_attribute_name(:cost_price_column) %>
        <br/>
        <%= f.text_field :cost_price_column, :class => 'fullwidth' %>
      <% end %>
    </div>
    <div class="four columns lh">
      <%= f.field_container :quantity_column do %>
        <%= f.label :quantity_column, Spree::Pricelist.human_attribute_name(:quantity_column) %>
        <br/>
        <%= f.text_field :quantity_column, :class => 'fullwidth' %>
      <% end %>
    </div>

    <div class="four columns lh">
      <%= f.field_container :desc_column do %>
        <%= f.label :desc_column, Spree::Pricelist.human_attribute_name(:desc_column) %>
        <br/>
        <%= f.text_field :desc_column, :class => 'fullwidth' %>
      <% end %>
    </div>

    <div class="four columns lh">
      <%= f.field_container :image_dir_column do %>
        <%= f.label :image_dir_column, Spree::Pricelist.human_attribute_name(:image_dir_column) %>
        <br/>
        <%= f.text_field :image_dir_column, :placeholder=> "/lib/images",:class => 'fullwidth' %>
      <% end %>
    </div>

    <div class="four columns lh">
      <%= f.field_container :parent_column do %>
        <%= f.label :parent_column, 'Столбец родителя' %>
        <br/>
        <%= f.text_field :parent_column, :class => 'fullwidth' %>
      <% end %>
    </div>

    <div class="four columns lh">
      <%= f.field_container :margin do %>
        <%= f.label :margin, Spree::Pricelist.human_attribute_name(:margin) %>
        <br/>
        <%= f.text_field :margin, :class => 'fullwidth' %>
      <% end %>
    </div>

  </div>

  <div class="col-sm-5">
    <h4>Характеристики</h4>
    <div class="row">
      <div class="col-sm-6">
        <div class="four columns lh">
          <%= f.field_container :property1_label do %>
            <%= f.label :property1_label, 'Название' %>
            <br/>
            <%= f.text_field :property1_label, :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns lh">
          <%= f.field_container :property2_label do %>
            <%= f.label :property2_label, 'Название' %>
            <br/>
            <%= f.text_field :property2_label, :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns lh">
          <%= f.field_container :property3_label do %>
            <%= f.label :property3_label, 'Название' %>
            <br/>
            <%= f.text_field :property3_label, :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns lh">
          <%= f.field_container :property4_label do %>
            <%= f.label :property4_label, 'Название' %>
            <br/>
            <%= f.text_field :property4_label, :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns lh">
          <%= f.field_container :property5_label do %>
            <%= f.label :property5_label, 'Название' %>
            <br/>
            <%= f.text_field :property5_label, :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns lh">
          <%= f.field_container :property6_label do %>
            <%= f.label :property6_label, 'Название' %>
            <br/>
            <%= f.text_field :property6_label, :class => 'fullwidth' %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="four columns lh">
          <%= f.field_container :property1 do %>
            <%= f.label :property1, 'Столбец со значением' %>
            <br/>
            <%= f.text_field :property1, :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns lh">
          <%= f.field_container :property2 do %>
            <%= f.label :property2, 'Столбец со значением' %>
            <br/>
            <%= f.text_field :property2, :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns lh">
          <%= f.field_container :property3 do %>
            <%= f.label :property3, 'Столбец со значением' %>
            <br/>
            <%= f.text_field :property3, :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns lh">
          <%= f.field_container :property4 do %>
            <%= f.label :property4, 'Столбец со значением' %>
            <br/>
            <%= f.text_field :property4, :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns lh">
          <%= f.field_container :property5 do %>
            <%= f.label :property5, 'Столбец со значением' %>
            <br/>
            <%= f.text_field :property5, :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns lh">
          <%= f.field_container :property6 do %>
            <%= f.label :property6, 'Столбец со значением' %>
            <br/>
            <%= f.text_field :property6, :class => 'fullwidth' %>
          <% end %>
        </div>
      </div>

  </div>
  </div>

  <div class="col-sm-4">
    <h4>Товарные опции для вариантов</h4>
    <div class="row">
      <div class="col-sm-6">
        <div class="four columns ">
          <%= f.field_container :otype1_label do %>
            <%= f.label :otype1_label , 'Название товарной опции' %>
            <br/>
            <%= f.text_field :otype1_label  , :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns ">
          <%= f.field_container :otype2_label do %>
            <%= f.label :otype2_label , 'Название товарной опции' %>
            <br/>
            <%= f.text_field :otype2_label  , :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns ">
          <%= f.field_container :otype3_label do %>
            <%= f.label :otype3_label , 'Название товарной опции' %>
            <br/>
            <%= f.text_field :otype3_label  , :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns ">
          <%= f.field_container :otype4_label do %>
            <%= f.label :otype4_label , 'Название товарной опции' %>
            <br/>
            <%= f.text_field :otype4_label  , :class => 'fullwidth' %>
          <% end %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="four columns ">
          <%= f.field_container :otype1 do %>
            <%= f.label :otype1 , 'Столбец товарной опции' %>
            <br/>
            <%= f.text_field :otype1  , :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns ">
          <%= f.field_container :otype2 do %>
            <%= f.label :otype2 , 'Столбец товарной опции' %>
            <br/>
            <%= f.text_field :otype2  , :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns ">
          <%= f.field_container :otype3 do %>
            <%= f.label :otype3 , 'Столбец товарной опции' %>
            <br/>
            <%= f.text_field :otype3  , :class => 'fullwidth' %>
          <% end %>
        </div>

        <div class="four columns ">
          <%= f.field_container :otype4 do %>
            <%= f.label :otype4 , 'Столбец товарной опции' %>
            <br/>
            <%= f.text_field :otype4  , :class => 'fullwidth' %>
          <% end %>
        </div>
      </div>

    </div>


  </div>

</div>

app/views/spree/admin/pricelists/edit.html.erb
<% content_for :page_title do %>
  <%= "Изменить Распознаватель" %>
<% end %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @pricelist } %>
<%= form_for [:admin, @pricelist], :html => { :multipart => true } do |f| %>
  <fieldset>
    <%= render 'form', f: f %>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'icon-ok' %>
      <span class="or">
        <%= Spree.t(:or) %>
      </span>
      <%= link_to_with_icon 'icon-remove', Spree.t('actions.cancel'), admin_pricelists_path, :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/pricelists/index.html.erb
<% content_for :page_title do %>
  <%= "Список Распознавателей" %>
<% end %>
<% content_for :page_actions do %>
    <%= link_to_with_icon 'add', "Новый распознаватель", new_admin_pricelist_path, { :remote => true, :class => "btn btn-success", :id => 'admin_new_pricelist' } %>
<% end %>
<div id="new_parser_wrapper"></div>
<% if @pricelists.blank? %>
  <div class="no-objects-found">
    <%= "Не создано ни одного распознавателя!" %>
  </div>
<% else %>
  <table class="table" id="listing_products">
    <colgroup>
      <col style="width:70%"></col>
      <col style="width:20%"></col>
      <col style="width:10%"></col>
    </colgroup>
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th>Название</th>
        <th class="actions" data-hook="admin_products_index_header_actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @pricelists.each do |pricelist| %>
        <tr id="<%= dom_id pricelist%>">
          <td class="align-center">
            <%= pricelist.name %>
          </td>
          <td class="actions" data-hook="admin_products_index_row_actions">
            <%= link_to_with_icon 'icon-edit', 'Изменить распознаватель', edit_admin_pricelist_path(pricelist), {:class => "edit", :no_text => true} %>
            <%= link_to_edit pricelist, url: edit_admin_pricelist_path(pricelist), no_text: true %>
            <%= link_to_with_icon 'icon-delete', 'Удалить распознаватель', admin_pricelist_path(pricelist), {:class => "delete", :no_text => true} %>
            <%= link_to_delete pricelist, url: admin_pricelist_path(pricelist), no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/pricelists/new.html.erb
<% content_for :page_title do %>
  <%= "Новый Распознаватель" %>
<% end %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @pricelist } %>
<%= form_for [:admin, @pricelist], :html => { :multipart => true } do |f| %>
  <fieldset>
    <%= render 'form', f: f %>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'ok' %>
      <span class="or">
        <%= Spree.t(:or) %>
      </span>
      <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_pricelists_path, :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/pricelists/new.js.erb
$("#new_parser_wrapper").html('<%= escape_javascript(render :template => "spree/admin/pricelists/new", formats: [:html], handlers: [:erb]) %>');
handle_date_picker_fields();
$("#table-filter").hide();
$("#admin_new_pricelist").parent().hide();

app/views/spree/admin/pricelists/new_import.html.erb
<% content_for :page_title do %>
  <%= "Загрузка и распознавание XLSX файлов" %>
<% end %>
<%= form_tag import_admin_pricelists_path, multipart: true do %>
  <fieldset class="no-border-top">
    <div class="row">
      <div class="four columns">
        <div class="field" data-hook="file">
          <%= label_tag Spree.t(:filename) %>
          <br>
          <%= file_field_tag :xlsx_file %>
        </div>
        <div class="field">
          <%= label_tag :pricelist, Spree::Pricelist.model_name.human %>
          <span>
            <%= select_tag :pricelist, options_for_select(Spree::Pricelist.all.map{|c| [c.name, c.id]}), :include_blank => true, :class => 'select2 fullwidth' %>
          </span>
        </div>
        <div class="field">
          <%= label_tag Spree.t(:starting_row) %>
          <br>
          <%= number_field_tag :starting_row, 1 %>
        </div>
      </div>
    </div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button "Загрузить", 'icon-download' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/product_synonims/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= f.field_container :name do %>
      <%= f.label :name, Spree::ProductSynonim.human_attribute_name(:name) %>
      <span class="required">*</span>
      <br/>
      <%= f.text_field :name, :class => 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>
</div>

app/views/spree/admin/product_synonims/index.html.erb
<% content_for :page_actions do %>
    <%= link_to_with_icon 'plus', Spree.t(:new_product_synonim), new_admin_product_product_synonim_path(@product), { :remote => true, :class => "btn btn-success", :id => 'admin_new_product_synonim' } %>
<% end %>


<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => :product_synonims} %>

<div id="new_product_synonim_wrapper"></div>
<% if @product_synonims.blank? %>
  <div class="no-objects-found">
    <%= Spree.t(:not_found) %>
  </div>
<% else %>
  <table class="table" id="listing_products">
    <colgroup>
      <col style="width:90%"></col>
      <col style="width:10%"></col>
    </colgroup>
    <thead>
      <tr data-hook="admin_product_synonims_index_headers">
        <th><%= Spree::ProductSynonim.human_attribute_name(:name) %></th>
        <th class="actions" data-hook="admin_product_synonims_index_header_actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @product_synonims.each do |product_synonim| %>
        <tr id="<%= dom_id product_synonim%>">
          <td class="align-center">
            <%= product_synonim.name %>
          </td>
          <td class="actions" data-hook="admin_products_index_row_actions">
            <%= link_to_delete product_synonim, url: admin_product_product_synonim_path(@product, product_synonim), no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/product_synonims/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_product_synonim) %>
<% end %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @product_synonim } %>
<%= form_for [:admin, @product, @product_synonim], :html => { :multipart => true } do |f| %>
  <fieldset>
    <%= render 'form', f: f %>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'icon-ok' %>
      <span class="or">
        <%= Spree.t(:or) %>
      </span>
      <%= link_to_with_icon 'icon-remove', Spree.t('actions.cancel'), admin_product_product_synonims_path(@product), :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/product_synonims/new.js.erb
$("#new_product_synonim_wrapper").html('<%= escape_javascript(render :template => "spree/admin/product_synonims/new", formats: [:html], handlers: [:erb]) %>');
handle_date_picker_fields();
$("#table-filter").hide();

app/views/spree/admin/shared/_pricelist_sidebar_menu.html.erb
<% if can? :admin, Spree::Pricelist %>
<ul class="nav nav-sidebar">
  <%#= tab Spree::Pricelist, url: new_import_admin_pricelists_path, icon: 'file', label: Spree::Pricelist.model_name.human(count: :many) %>
  <%= main_menu_tree 'Импорт прайслиста', icon: "th-large", sub_menu: "pricelist", url: "#sidebar-pricelist" %>
  <%#= tab Spree::Pricelist, url: new_import_admin_pricelists_path, icon: "th-large" %>
</ul>
<% end %>

app/views/spree/admin/shared/_pricelists_sidebar_menu.html.erb
<% if can? :manage, Spree::Pricelist %>
  <ul class="nav nav-sidebar">
    <%= main_menu_tree Spree.t(:new_import), :icon => 'file', sub_menu: "pricelist", url: "#sidebar-pricelist" %>
  </ul>
<% end %>

app/views/spree/admin/shared/sub_menu/_pricelist.html.erb
<ul id="sidebar-pricelist" class="collapse nav nav-pills nav-stacked" data-hook="admin_pricelist_sub_tabs">
  <%= tab :new_import, url: new_import_admin_pricelists_path, match_path: "g" %>
  <%= tab :conflicts, url: admin_conflicts_path, match_path: "g" %>
  <%= tab :pricelists, url: admin_pricelists_path, match_path: "g" %>
</ul>